### ISSUE TITLE
Click links on desktop without having to first bring it into focus

### ISSUE THREAD

**Issue by jonahclarsen** [sindresorhus/Plash#101]
**Is your feature request related to a problem? Please describe.**

I have a gallery of my favourite album artwork where each one can be clicked on to open it in Apple Music. Hovering over links on the desktop (in browsing mode of course) does not allow me to click anything until I first click once to bring the desktop into focus.

**Describe the solution you'd like**

It would be great if links just worked without having to first bring the desktop into focus, particularly when all windows have been hidden with Cmd+H, but it would be even better if it links worked without having to first bring the desktop into focus even when the desktop is partially visible behind an active window.

Similarly, I would like an animation to play on a mouseover or mouseenter event without the desktop needing to be the active window for the mouseover/mouseenter/mouseleave events to be triggered.

Thanks!

**Comment by sindresorhus** [comment]
I don't think mouseover/mouseenter events is possible, but I'll add support for clicking links directly.

**Comment by sindresorhus** [comment]
This is included in the latest update: https://apps.apple.com/no/app/plash/id1494023538?mt=12

**Comment by jonahclarsen** [comment]
> This is included in the latest update: https://apps.apple.com/no/app/plash/id1494023538?mt=12

Thanks for considering this issue. However, the newest update breaks my use case even further. Before, I could click once to bring it into focus if I wanted the page to receive mouseover events (which trigger a visually appealing animation). But now, clicking on the desktop when it is out of focus just immediately opens the links, and I can't even click on a blank spot on the desktop to bring it into focus.

I would appreciate it very much if you could either simply make the last update's change optional in the app's preferences, or make it possible to bring the desktop into focus (so it can receive mouseover events) at least by clicking on a blank part of the website (I can't even click on an image with an <a href="#"> to do that at this point) if you can't make it receive mouseover/out events when it is inactive/partially visible.

**Comment by sindresorhus** [comment]
I looked into this again and it's [simply not possible](https://github.com/feedback-assistant/reports/issues/298) to have mouseover events when Plash is not focused.

I think the current behavior is the correct one. Mouseover is just a bonus. It's not important. So I will not change the default or add a setting to the UI.

**Comment by sindresorhus** [comment]
> and I can't even click on a blank spot on the desktop to bring it into focus.

I cannot reproduce this. If I click on any non-link content, the window gets focus and mouseover works.

What macOS version and have you tried different websites?

**Comment by jonahclarsen** [comment]
12.2.1, haven't tried other websites.

Sometimes clicking on a non-link brings it into focus - the problem is difficult to reliably recreate, but it seems to happen mostly when refreshing the desktop page while another window is in focus.

I wish it were possible to downgrade apps in the mac app store >.< Maybe now it's time to learn to build from source in Swift...

------- Original Message -------
