### ISSUE TITLE
Update the url after user interactivity

### ISSUE THREAD

**Issue by KingMario** [sindresorhus/Plash#108]
In browsing mode, the user may click a link on the page to navigate. Could it be configurable for each site that the url can be tracked and updated to the site setting?

That will be useful while I'm doing some casual reading of, for example, angular.io online documentation.

Thanks.

**Comment by sindresorhus** [comment]
Added in the latest update: https://apps.apple.com/no/app/plash/id1494023538?mt=12

After navigating to a new page, right-click the page to update the URL for the stored website.
