### ISSUE TITLE
Unable to Log In to Google

### ISSUE THREAD

**Issue by stdavis** [sindresorhus/Plash#109]
**Describe the bug**

When I attempt to log into any google site I get the following error message after I type in my email:

```
Couldn’t sign you in
This browser or app may not be secure. [Learn more](https://support.google.com/accounts/answer/7675428?hl=en-US)
Try using a different browser. If you’re already using a supported browser, you can try again to sign in.
```

**To reproduce**

1. Uncheck the "Open external links in default browser" option in advanced preferences
2. Add `gmail.com` as a website
3. Click on the "Sign in" button
4. Enter your email/phone and click "Next"

**Expected behavior**

I expected to be able to successfully sign into google.

**Screenshots**

![image](https://user-images.githubusercontent.com/1326248/187482475-62cd48ee-2385-423a-b859-2322ed6c9c5b.png)

**Info**

 - macOS version: 12.5.1
 - Plash version: 2.11.1 (42)

**Additional context**

None that I can think of. I have definitely been able to do this in the past but I don't know how long ago it was. I use Google to sign into a Notion dashboard that I use as a desktop via this awesome app.

**Comment by sindresorhus** [comment]
Fixed in the latest update: https://apps.apple.com/no/app/plash/id1494023538?mt=12

**Comment by stdavis** [comment]
Confirmed as fixed. Thank you so much for the quick response. I love this project!
