### ISSUE TITLE
Layer multiple Plashes

### ISSUE THREAD

**Issue by imaverage** [sindresorhus/Plash#110]
**Is your feature request related to a problem? Please describe.**

A. I want to display a website (like a digital clock) with the background transparent so you can see the wallpaper.
B. I also want to display an animated wallpaper (like a subtle gif of a sunset).

I am currently forced to choose A with a static desktop that I control via my Mac, or B without a clock.

**Describe the solution you'd like**

I would like to have both A and B simultaneously.

In effect, my desktop would display my native Mac wallpaper (lets say the color blue). On top of that, it would display layer B (an animated picture that takes up the full screen). (at this point, you don't see the native wallpaper anymore). and on top of that, I would like to render A -- a website that shows a clock but I set the css such that the white background is transparent.

The net result is that you dont see my Mac native wallpaper, but rather a digital clock atop an animated wallpaper of a sunset.

**Describe alternatives you've considered**

Implement a local file with the digital clock and have the wallpaper of that html file set to the gif I want. This is not scalable nor is it user friendly (if i wanted to change the wallpaper, I now have to touch code and possibly recompile stuff).

**Additional context**

**Comment by sindresorhus** [comment]
Thanks for the suggestion. This is unfortunately not something I plan to add. There's simply not enough demand for it to justify the complexity of it, both in code and user-interface.

As a workaround, you could use the CSS/JS setting to inject what you want into the website.
