### ISSUE TITLE
Expose API to get Calendar and Reminder access to view in page

### ISSUE THREAD

**Issue by muuvmuuv** [sindresorhus/Plash#112]
**Is your feature request related to a problem? Please describe.**

I would like to view my Apple calendar and reminders in my web page, would be great to get access to them through a JS API like `window.Plash.events(params:)`.

**Describe the solution you'd like**

JS API like `window.Plash.events(params:)`

**Describe alternatives you've considered**

I have tried setting up a docker Swift HTTP server that serves these information but was not able to finish it. That way I could have my local website and the Swift server in containers and these talk to each other since Apple does not have such an API.

**Additional context**

/

**Comment by sindresorhus** [comment]
Thanks for the suggestion. This is unfortunately not something I plan to add. There's simply not enough demand for it to justify the complexity of it.

**Comment by sindresorhus** [comment]
These may be helpful: https://github.com/keith/reminders-cli
