### ISSUE TITLE
Add ability to save downloaded images to hard drive

### ISSUE THREAD

**Issue by 0ldM4cM4n** [sindresorhus/Plash#113]
Sindre, it would really be great if you could add the ability to Plash to save downloaded images to a specified folder on one’s hard drive. I use satellite images from NOAA to create weather animations. Thanks for your consideration.

---
${params.get('metadata') ?? ''}

**Comment by sindresorhus** [comment]
I unfortunately have no plans to support that. Plash is not a browser. It's meant to be used as a dynamic wallpaper. The current "browsing mode" is only intended for logging into services and clicking links. Adding lots of browser functionality is a slippery slope.
