### ISSUE TITLE
multiple spaces with different sites simultaniously

### ISSUE THREAD

**Issue by 11100010** [sindresorhus/Plash#115]
Hi all,
I can't figure it out how to set more than one space with different sites. 

Is it possible to be done? Or it's just not a feature yet?

ps: I've found out that running different versions of Plash at once is a solution, but it's apparently not ideal.

Thanks so much for helping!

**Comment by sindresorhus** [comment]
This is not really possible. macOS does not provide enough capabilities to developers for apps to be able to open in specific spaces.

**Comment by sindresorhus** [comment]
> ps: I've found out that running different versions of Plash at once is a solution, but it's apparently not ideal.

This is the only workaround for now.
