### ISSUE TITLE
White menu bar on all wallpapers

### ISSUE THREAD

**Issue by d-beldy** [sindresorhus/Plash#116]
**Describe the bug**

The menu bar stays white whatever the wallpaper color is although it must adapt to the colors underneath. 

**To reproduce**

Nothing to reproduce, the menu bar is always white. 

**Expected behavior**

The menu bar should adapt to the wallpaper color, as it is with the macOS stock wallpapers. 

**Screenshots**
<img width="1280" alt="Снимок экрана 2022-11-27 в 11 12 14" src="https://user-images.githubusercontent.com/99273009/204123717-00a58f28-b1b7-4132-bb6b-960f1bfa7cd8.png">
<img width="1280" alt="Снимок экрана 2022-11-27 в 11 14 23" src="https://user-images.githubusercontent.com/99273009/204123761-0f1b3b47-1816-4e29-bad3-dd4e4788bbc2.png">

**Info**

 - macOS version: Ventura 13.0.1
 - Plash version: 2.12.0 (47)

**Comment by sindresorhus** [comment]
The menu bar adapts its color from the actual system wallpaper. Plash is not actually a wallpaper, but rather runs right above the wallpaper. So Plash cannot influence the menu bar color.
