### ISSUE TITLE
Toggle to Allow Background to go Behind Menu Bar to Rectify App Exposé

### ISSUE THREAD

**Issue by novyboy** [sindresorhus/Plash#122]
**Is your feature request related to a problem? Please describe.**

The menu bar briefly disappears when you trigger the App Exposé or Mission Control _(though it isn't visible for long during Mission Control)_.

**Describe the solution you'd like**

I'd like a toggle to select whether or not to render the selected website behind the menu bar.

**Describe alternatives you've considered**

Unless there's a way to automatically adapt based on the views I mentioned, the toggle seems like the easiest and most straightforward method to implement without introducing issues of changing viewport height.

**Additional context**

I'm aware that this issue has been brought up before, but that was in regards to a one pixel bleed, whereas this is in regards to the App Exposé.

**Comment by sindresorhus** [comment]
There's a hidden setting for this in the latest update. Run the following in the Terminal app:

```
defaults write com.sindresorhus.Plash extendPlashBelowMenuBar true
```
