### ISSUE TITLE
Plash Quits on Screen Saver or Sleep or Lock Screen

### ISSUE THREAD

**Issue by novyboy** [sindresorhus/Plash#123]
**Describe the bug**

When the computer enters sleep, goes to the lock screen, or goes to the screen saver, Plash quits.

**To reproduce**

1. Go to  > Lock Screen in top left of the menu bar
2. Log back in
3. Plash will no longer be open or in the menu bar

OR

1. Go to  > Sleep in top left of the menu bar
2. Wake the computer
3. Plash will no longer be open or in the menu bar

OR 

1. Open Shortcuts
2. Go to File > New Shortcut in the menu bar
3. Add the `Start screen saver` action
4. Run the Shortcut
5. Wake the computer
6. Plash will no longer be open or in the menu bar

**Expected behavior**

Plash and the website should remain open even after following these steps, and no reloading should occur.

**Info**

 - macOS version: Ventura 13.1
 - Plash version: 2.13.0 (49)

**Additional context**

If Plash's Settings panel is open, Plash will not exit, but the website will reload.

Also interesting to note, these steps will not trigger the issue: 
1. Open System Settings
2. Go to Screen Saver
3. Select a screen saver
4. Click Preview
5. Wake the computer
6. Plash will still be open and in the menu bar

**Comment by novyboy** [comment]
@sindresorhus Thanks so much for your quick work! The quitting bug is completely fixed! 
Unfortunately, the website still has to reload when you log back in or wake your computer up, which isn't the worst, but I thought you should know anyways in case you can think of any way to fix that

**Comment by sindresorhus** [comment]
> Unfortunately, the website still has to reload when you log back in or wake your computer up, which isn't the worst, but I thought you should know anyways in case you can think of any way to fix that

That's an intentional feature. There are many things that can have changed during sleep: screens, times, time zones, etc. Reloading the website ensures it's correct.
