### ISSUE TITLE
Show Mac Calender (iCal) as background, too?

### ISSUE THREAD

**Issue by ingozoell** [sindresorhus/Plash#137]
Hi, 

is this possible or planed?
Regards, Ingo

**Comment by sindresorhus** [comment]
There's no way to show the Calendar app, but you could show your iCloud calendars: https://github.com/sindresorhus/Plash/discussions/136#discussioncomment-6725052

**Comment by ingozoell** [comment]
Hi,

thanks.

I use macOS 13.5 – I got just Calender-Login Screen
iCloud for web view is active.

https://i.imgur.com/quf16aZ.png

**Comment by ingozoell** [comment]
The "Browsing Mode did it for me, great"
https://i.imgur.com/IYSlNOQ.png
