### ISSUE TITLE
"Show on [space]" setting doesn't persist across restarts

### ISSUE THREAD

**Issue by jonahclarsen** [sindresorhus/Plash#144]
**Describe the bug**

I always have two spaces (right one for music). I have my Plash desktop only showing on my right one. When I restart my PC and Plash starts, it always defaults to the leftmost space, and I have to manually change it back to the right space. I have Plash auto-start on login.

I know I can set it to show on all spaces, but I don't want it on my leftmost space.

**To reproduce**

1. Ensure Plash is set to start on login.
2. Set your desktop to any space other than the leftmost one.
3. Restart your PC.
4. Notice that when Plash starts, it shows on the leftmost space rather than the one you left it on.

**Info**

 - macOS version: 14.0 (happened on 13.x too)
 - Plash version: 2.13.3

**Comment by sindresorhus** [comment]
macOS does not let apps specify which space to open an app in, so this is unfortunately not possible.

**Comment by jonahclarsen** [comment]
This is unfortunate!

I may be a bit confused here though - why does it matter what space it opens into? Can't you store the last chose "Show in [space]" setting as a preference and reload that when the app starts?

**Comment by sindresorhus** [comment]
Are you talking about displays? There is no "Show in [space]" setting.

**Comment by jonahclarsen** [comment]
Oh yeah sorry, I was confused. I am talking about spaces, not displays. I guess I was thinking you could have a hidden "show on space" pref that persists across restarts to fix this issue.
