### ISSUE TITLE
load web page with browser engine that supports webgpu

### ISSUE THREAD

**Issue by tiye** [sindresorhus/Plash#146]
**Is your feature request related to a problem? Please describe.**

At first I was searching for wallpaper with shader. Then I found Plash and it seem it's not working with webgpu web pages. I also tried WebGL and it's working.

**Describe the solution you'd like**

Since I have Chrome installed in my OS, any chance to render page with Chrome? My guess is currently it rendering with something like Safari, but it didn't run alert from the page that warning webgpu not supported.

**Describe alternatives you've considered**

webgl is ok, just not as nice without compute shader.

**Additional context**

loading shadertoy or computetoy in fullscreen would be a nice option of dynamic wallpaper.

**Comment by sindresorhus** [comment]
WebGPU is not supported by Safari. When it is, it will be supported here too.

I have no plans to support Chrome in any form. It would require rewriting the whole app.

**Comment by sindresorhus** [comment]
WebGPU is not supported by Safari. When it is, it will be supported here too.

I have no plans to support Chrome in any form. It would require rewriting the whole app.

**Comment by tiye** [comment]
hope WKWebView could make it earlier.
