### ISSUE TITLE
Display Plash in true fullscreen

### ISSUE THREAD

**Issue by 8utl3r** [sindresorhus/Plash#148]
Plash doesn't go up all the way to the top pixel. I use Bartender 5 and pill shaped seperated menu bars. I'd love if plash could be the background there as well. Would this be difficult?

---
Plash 2.14.1 (56) - com.sindresorhus.Plash
macOS 14.1.1
Mac15,6

**Comment by sindresorhus** [comment]
This is not possible. Bartender 5 works by creating a fake window above everything that draws the wallpaper image you have set in the System Settings and then the new menu bar style above that again.

You could ask Bartender to support also including any windows shown at the desktop window level, which is where Plash shows its window.
