### ISSUE TITLE
the window size of the opened pop-up page cannot be changed (macos14)

### ISSUE THREAD

**Issue by lumengxin** [sindresorhus/Plash#149]
**Describe the bug**

After system upgrade, the window size of the opened pop-up page cannot be changed。

Maximize and minimize buttons are not clickable, the window cannot be resized by dragging it

**Screenshots**

<img width="918" alt="image" src="https://github.com/sindresorhus/Plash/assets/39377926/9bf00828-67ee-4f9e-90c1-61c7dd9a88ba">

**Info**

 - macOS version: macOS 14.1.1
 - Plash version: latest

**Comment by sindresorhus** [comment]
The website decides whether or not it should be resizable. Is it resizable if you open the same thing in Safari?
