### ISSUE TITLE
Please provide proxy support.

### ISSUE THREAD

**Issue by chengyongru** [sindresorhus/Plash#153]
Hello, I want a feature that allows setting a proxy address for each website, similar to the Proxy SwitchyOmega plugin in Chrome. As a Chinese user, I often need to configure a proxy server in order to access websites like Google. In the shell, I would use `export https_proxy=127.0.0.1:23457` to achieve this task. However, Plash does not currently have an explicit function for this purpose. It would be less ideal if all traffic is routed through system-level proxies as it lacks elegance.Thank you!

**Comment by sindresorhus** [comment]
Sorry, I don't plan to add this. It's simply too much work compared to the demand.

You could instead use an app like http://www.proxifier.com to add proxy just for certain apps.

**Comment by chengyongru** [comment]
Thank you for your response. I didn't find anything like proxifier before. For sure,proxifier is already meeting my needs.
