### ISSUE TITLE
Plash always asks for Basic Auth login even when it's already saved

### ISSUE THREAD

**Issue by StashPowerUser** [sindresorhus/Plash#157]
**To reproduce**

1. Set up a website that uses basic auth
2. Login to basic auth with prompt
3. Restart plash
4. See plash load website logged in but still show login prompt

If this is intentional behavior it would be nice to have an option to disable the login prompt after logging in.

**Comment by sindresorhus** [comment]
If you try the URL `https://jigsaw.w3.org/HTTP/Basic/` with `guest` as username and password in Plash, does it prompt again on the next launch? If not, this maye be a server issue.

**Comment by StashPowerUser** [comment]
That seemed to work as expected.

I'll try to isolate what's going on better on my end and re-open this with more detail if I do.

**Comment by StashPowerUser** [comment]
I was able to replicate similar behavior in a safari private window (but not a regular window)

Looking at the network inspector, the issue seems to be related to websocket (wss://) connections on the same domain.

I'll see if I can put together an example site to show the issue later.

**Comment by StashPowerUser** [comment]
It is an issue with web sockets, for my use case I was able to exclude the web socket endpoint from basic auth and that resolved the issue in plash.
