### ISSUE TITLE
Failed build in XCode 15.2

### ISSUE THREAD

**Issue by keaukraine** [sindresorhus/Plash#159]
Build fails in XCode 15.2 with an error `Command PhaseScriptExecution failed with a nonzero exit code`.

**To reproduce**

1. Get sources.
2. Run app.

**Screenshots**

![image](https://github.com/sindresorhus/Plash/assets/414072/32769eca-5702-4813-a828-f356abf4f0a6)

 - macOS version: Sonoma 14.3.1
 - XCode version: 15.2
 - Plash version: latest master

**Comment by sindresorhus** [comment]
You need SwiftLint

**Comment by keaukraine** [comment]
Thank you, SwiftLint fixed it.
