### ISSUE TITLE
HUD (Heads-Up Display) via Non-Browsing Mode to the Front

### ISSUE THREAD

**Issue by willrogers007** [sindresorhus/Plash#160]
I'd like to write a heads-up display page and immediately I thought to reach for Plash, where the display would be above other windows but pass-through for mouse interaction.

Currently there's an option for having Plash be at the front during browsing mode, but it's "in the way" in terms of not being transparent to the mouse. What I would need for this is for there to have Plash be at the front, and for it to not be in browsing mode.

Is that something I can help with on the Xcode side?

**Comment by sindresorhus** [comment]
This is outside the scope of Plash, but it should be easy to modify the source to achieve this. I cannot provide any support for that though.

https://github.com/sindresorhus/Plash/blob/a2356b15b6b09940bc0808c8a33ba8fc677a180a/Plash/DesktopWindow.swift#L19-L29
