### ISSUE TITLE
升级到macOS 14后图片显示模糊

### ISSUE THREAD

**Issue by YashiroKirara** [sindresorhus/Plash#161]
请问plash底层使用的是什么浏览器内核呢？
最近发现一个问题。我自己做了一个类似相册的本地网页，展示本地磁盘的图片。在升级到MacOS 14之前，没有问题，升级到14之后，发现图片显示变模糊了。
图片是以div的background属性显示的，我按照网上的教程，为div增加了image-rendering属性，但是仍然感觉有些模糊，不如macOS 13时清晰。请问有什么办法吗？谢谢！

---
Plash 2.15.0 (57) - com.sindresorhus.Plash
macOS 14.4.1
MacBookPro17,1

**Comment by sindresorhus** [comment]
Plash uses the Safari engine that comes with macOS.
