### ISSUE TITLE
Publish the app on homebrew-cask

### ISSUE THREAD

**Issue by marcofugaro** [sindresorhus/Plash#17]
https://github.com/Homebrew/homebrew-cask

With brew cask you can install mac apps from the command line. I use it in my setup scripts to install all the mac apps I need.

Could you publish this app on brew cask? So an user would be able to install the app with `brew cask install plash`

**Comment by sindresorhus** [comment]
Sorry, not interested in doing that. I would have to make a non-Mac App Store release, which requires a lot of overhead.
