### ISSUE TITLE
Can't find the button on the menu

### ISSUE THREAD

**Issue by biubiubiu-50** [sindresorhus/Plash#172]
**Describe the bug**

I download plash from App store. But after I opened it, nothing happened and I cannot find the plash logo anywhere on the desktop.

**Screenshots**
<img width="779" alt="image" src="https://github.com/user-attachments/assets/d38cd5de-7bf6-4a54-8c77-b66117c9f8fe">
<img width="321" alt="image" src="https://github.com/user-attachments/assets/6b0249d2-4d66-42b7-a8da-56d0bf2b66df">

**Info**

 - macOS version: 14.5
 - Plash version: the one in the app store

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/Plash?tab=readme-ov-file#the-app-does-not-show-up-in-the-menu-bar
