### ISSUE TITLE
Scaled images for retina screens

### ISSUE THREAD

**Issue by RyanRoberts** [sindresorhus/Plash#20]
Is it possible to or could you add the ability to scale images to fit the desktop area?

Take your Unsplash for example, a full resolution image is cropped as it's displayed full size. You have to use the lower res version of the screen to get it to fit and of course this is blurry.

Great app though 👍

---
Plash 1.0.0 (1) - com.sindresorhus.Plash
macOS 10.15.2
MacBookPro15,1

**Comment by sindresorhus** [comment]
That's strange. It's works fine for me. Did you try the Unsplash example in the readme?

**Comment by RyanRoberts** [comment]
You're right, the example resolution isn't right for my screen but https://source.unsplash.com/random/3360x2056?puppy does downsize correctly. Maybe the source image wasn't well suited to the aspect ratio.
