### ISSUE TITLE
Save multiple sites and possibly toggle them with ⌘ + number value

### ISSUE THREAD

**Issue by withoutwax** [sindresorhus/Plash#24]
It would be great to be able to save multiple website and switch them like tabs with ⌘ + Numeric key!

**Comment by sindresorhus** [comment]
What's your use-case? Plash was really meant to set and forget. If you need manually toggle between websites, maybe just put them in browser tabs?

I am considering some kind of playlist functionality (https://github.com/sindresorhus/Plash/issues/4), that would automatically switch between URLs and also let you manually skip.

**Comment by withoutwax** [comment]
Thanks for the reply! If you are already considering some kind of playlist functionality, then that solves my suggestion. As an indecisive person, I thought it would be great to be able to save multiple sits that I wish I can see on my desktop and load them whenever I want.

I think the reason why I bring this up is that I am starting to see this app to be used as a personal dashboard - which sort of departs from your original intention for your application. You originally considered this app to be more of a desktop wallpaper, but due to the potential & interactivity, I am also seeing as a powerful personal dashboard for all the data I want.

Either way, since you are already considering to save multiple site, I think I am good with it 👍

**Comment by tborychowski** [comment]
What about showing multiple sites at the same time? (next to each other)
I'm on a large monitor and would like to see several feeds (e.g. twitter, reddit, rss) side by side, in columns.
I tried creating a simple html with iframes, but a lot of sites prevent iframing them.

**Comment by sindresorhus** [comment]
> What about showing multiple sites at the same time? (next to each other)

That is unfortunately outside the scope of Plash.

> I tried creating a simple html with iframes, but a lot of sites prevent iframing them.

Yeah, that's a bummer. You could potentially set up a local proxy server that proxies requests and strips the iframe busting header.
