### ISSUE TITLE
Add support for showing a local file

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/Plash#3]
This is already partly implemented (see the TODOs):

https://github.com/sindresorhus/Plash/blob/03648fdbfc7d3020e111e9778ae86e4d31efbc4f/Plash/AppDelegate.swift#L148-L182

**Comment by sindresorhus** [comment]
@Matt-Gleich I have implemented this now. Would you be able to test it out?

[Plash-local.zip](https://github.com/sindresorhus/Plash/files/4080527/Plash-local.zip)

**Comment by Matt-Gleich** [comment]
Works on mine! Could there be a way to just choose an HTML file instead of it having to be index.html?

**Comment by sindresorhus** [comment]
Why? There's a reason I did it like this. Because of sandboxing, Plash only gets access to what you pick in the open panel. It needs access to the related files too, so it wouldn't be enough to just pick a HTML file. It needs to pick the directory. So to support picking a custom HTML file, Plash would have to prompt the user twice. First, for the HTML file and then for its directory. Didn't seem worth the complication nor worse UX for the user.

**Comment by Matt-Gleich** [comment]
I just thought it would've been nice to have. Can you not just get the directory from the loaded in file? If not thats fine I was just wondering.

**Comment by sindresorhus** [comment]
I can get the path to the directory. That's just removing the last path component. I just cannot get read **access** to it. Permissions in sandboxed apps are very strict, unfortunately.

**Comment by Matt-Gleich** [comment]
Ok, it's not like its that big of a deal.

**Comment by sindresorhus** [comment]
There's an update in the App Store now with this.
