### ISSUE TITLE
Global Shortcut

### ISSUE THREAD

**Issue by RyanRoberts** [sindresorhus/Plash#30]
At the moment I believe the only way to trigger Browsing Mode is to activate Plash from the menu bar and then select the mode or hit Command + B.

It would be great if we could trigger browsing mode from anywhere at any time through a global shortcut. I have Trello set as my desktop so half the time I'm viewing Plash I'm also interacting with it.

I've tried creating a solution to this using Better Touch Tool but had no luck.

Thanks.

**Comment by sindresorhus** [comment]
I never intended "Browser Mode" to be something you use a lot. It's meant to set up a website initially.

Wouldn't it be better to use a pinned browser tab for your use-case?

**Comment by willrogers007** [comment]
Hey! <3333 love the app!

Regarding the thread: I second this feature request!

> Wouldn't it be better to use a pinned browser tab for your use-case?

Isn't having a desktop-based browser the _ultimate_ form of pinned browser tab?

**Interim solution**
Currently I have a Keyboard Maestro shortcut setup to click on the Plash menu bar icon (with specific X, Y coords), do ⌘B, and restore mouse cursor location. Timing is a bit tricky at times, as the menu expansion might not appear in time for the ⌘B to trigger the action, so my current solution is not exactly ideal. Looking to see if I can adjust & rebuild the app via Xcode to fit my needs, but —being an Xcode noob— I'm crossing my fingers that it'll work out.

**Practicality of feature request**
I suspect for this global shortcut feature to be of general practical use in Plash, there would need to be some way of setting/adjusting the shortcut so as not to stomp on user settings.

I know this may smell like feature scope creep, but this is indeed a feature my use case beckons for. At least it sounds like I'm not alone, so I'm adding my +1 in here with some thoughts. Perhaps if I am able to rebuild this, I'll likely fork and eventually submit a pull request if this feature is found acceptable.

**Comment by sindresorhus** [comment]
An update is out with this feature. Just go to https://apps.apple.com/no/app/plash/id1494023538?mt=12 and click "Update".
