### ISSUE TITLE
transparent mode

### ISSUE THREAD

**Issue by ranrinc** [sindresorhus/Plash#31]
is there away for me to embeded single PNG which solid picture but the rest is transparent so I will be able to put a logo over my current wallpaper?

**Comment by sindresorhus** [comment]
This was implemented in the latest version. Just just in the Mac App Store.

**Comment by ranrinc** [comment]
@sindresorhus How? any guide for this?

**Comment by sindresorhus** [comment]
See https://github.com/sindresorhus/Plash/issues/1#issuecomment-573513816
