### ISSUE TITLE
Allow alert() and confirm() to shows up

### ISSUE THREAD

**Issue by Kiyozz** [sindresorhus/Plash#40]
**Is your feature request related to a problem? Please describe.**

JavaScript's `confirm()` and `alert()` does not appears.

**Describe the solution you'd like**

Popups shows up at the top of the screen.

**Describe alternatives you've considered**

In reflection.

**Additional context**

Example: use [manifest.app](https://manifest.app) and try to delete a note.

**Comment by sindresorhus** [comment]
This is now out. You'll have to go to https://apps.apple.com/us/app/plash/id1494023538?mt=12 and click "Update".

**Comment by Kiyozz** [comment]
Good job! Keep the good way! 😊
