### ISSUE TITLE
Keyboard text replacement not working

### ISSUE THREAD

**Issue by Kiyozz** [sindresorhus/Plash#43]
**Describe the bug**

Keyboard text replacement not working in the webview.

**To reproduce**

1. Setup a text replacement in MacOS settings (i.e. `tt` -> `tutu`)
2. Setup the url of webview to `manifest.app`
3. Create a note
4. Try to use the replacement -> not working

On Chrome, text replacement works. 

**Expected behavior**

Text replacement works: `tt` should be `tutu` in the note

**Info**

 - macOS version: 10.15.2
 - Plash version: 1.4.0

**Comment by sindresorhus** [comment]
I tried https://www.manifest.app in Safari and I didn't get any text replacement there either. Can you try?

**Comment by Kiyozz** [comment]
It seems to be a Manifest.app "issue".

the textareas has `spellcheck=false` that disable MacOS replacement. Chrome ignore it. 

Is this possible to inject custom JavaScript so I can change all textarea spellcheck attribute?

**Comment by sindresorhus** [comment]
Not yet, but it's planned (#27).

However, I would recommend opening an issue on https://github.com/jonathontoon/manifest/issues. I don't see why a note app would disable spell checking...

**Comment by Kiyozz** [comment]
Thanks! Issue filled!
