### ISSUE TITLE
AppleScript support

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/Plash#44]
Could be useful to programmatically control Plash. For example, download some image off the internet, wrap it in some HTML and load it. We could support loading a URL, local file, or a HTML string.

This is not something I plan to work on, but PR welcome if anyone needs this. Start a discussion here about scope and what actions and info should be supported before doing any code though.

If you decide to work on this, you're expected to also write docs, both API docs and a user guide.

**Comment by imaverage** [comment]
>  For example, download some image off the internet, wrap it in some HTML and load it.

could just use an auxiliary script that does this, and hack a plash refresh api by just killing the process and restarting it. that's what i currently do.

**Comment by sindresorhus** [comment]
I have decided to pass on this in favor of #45. AppleScript is just too archaic and annoying to implement.
