### ISSUE TITLE
URL scheme support

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/Plash#45]
It would be useful to be able to open a new URL in Plash programmatically.

I'm thinking:

```
open -g 'plash:add?url=https://sindresorhus.com/plash'
```

Or in AppleScript:

```
do shell script "open -g 'plash:add?url=https://sindresorhus.com/plash'"
```

I have an implementation for this for another app of mine I can reuse, so I just need to clean that up and add it to Plash.

Note: Document that it can also handle file URLs to local files.

Also `plash:reload`.

**Comment by NeighNeighNeigh** [comment]
Would be lovely if other commands would be supported programatically (Toggle Browsing mode, Next / Previous, etc). That way I could set up [Alfred](https://www.alfredapp.com/) to control Plash

**Comment by sindresorhus** [comment]
@NeighNeighNeigh Yes, I plan to support other commands too.

For now, though, you could work around it by setting keyboard shortcuts for those commands in the preferences and then use Alfred to trigger those keyboard shortcuts: https://www.alfredapp.com/help/workflows/outputs/dispatch-key-combo/

**Comment by NeighNeighNeigh** [comment]
Oh yeah that’s a nice little workaround :)

**Comment by sindresorhus** [comment]
This is now supported.

Get the latest version: https://apps.apple.com/no/app/plash/id1494023538?mt=12

And see:
https://github.com/sindresorhus/Plash#scripting
