### ISSUE TITLE
Support Print Styles

### ISSUE THREAD

**Issue by hu0p** [sindresorhus/Plash#46]
**Is your feature request related to a problem? Please describe.**

Some sites have really nice print styles for certain pages. For example, they often hide the header and footer. This would make them cleaner to display on a desktop.

**Describe the solution you'd like**

A toggle in the app preferences to emulate print styles similar to the one in Chrome devtools.

**Comment by sindresorhus** [comment]
Do you know how DevTools emulates print style?

**Comment by hu0p** [comment]
Nope, I'm not sure.

**Comment by sindresorhus** [comment]
I looked into this. It's possible, but hacky and probably doesn't cover all cases:

```js
for (const link of document.querySelectorAll('link[media="print"]') {
	link.removeAttribute('media');
}

for (const style of document.querySelectorAll('style')) {
    style.textContent = style.textContent.replace(/@media print/gi, '@media screen');
}
```

That leaves external CSS stylesheets with `@media print`. Not sure yet how to best handle those. We could maybe download the external CSS file locally, remove the `link` reference, modify the downloaded CSS, and then embed it back into the site in a `style` tag. However, this might change things and how the site look. Needs to be well-tested.

I'm open to other ideas.

**Comment by sindresorhus** [comment]
I think we could now use https://developer.apple.com/documentation/webkit/wkwebview/3516410-mediatype for this.

**Comment by sindresorhus** [comment]
> Some sites have really nice print styles for certain pages.

@hu0p Would you be able to share some websites with nice distinctive print styles? I need it for testing.

**Comment by hu0p** [comment]
@sindresorhus 

I did have one really great example (which inspired the original idea) where we had a flight calendar on a small regional airline that would print as a plain calendar, but it looks like dramatically changing circumstances around flights (triggered by you know what) have led to it being distributed as a PDF instead. I think searching for some examples made me realize I don't know if this feature is necessary anymore or as necessary as I thought. Custom CSS should cover most cases where the header and footer could stand to be hidden, for example.

That being said, I did find one example in google Docs. Print emulation there makes the page look like, well, the document to be printed. However, it also disables the interactive functionality of the docs. So someone who wished to use it as a sort of static notepad for their BG could do so, but it would require a couple of hotkey presses to make it work (toggle browsing mode and toggle print emulation). 

Maybe it's still worth including for the sake of completeness? I'll leave it up to you, of course. I've been fiddling with Swift a bit in my free time, and I made it halfway to submitting a PR for this, but haven't gotten around to finishing it.

**Comment by hu0p** [comment]
Oh, it looks like it could also be applied to Google Calendar (hides the left sidebar). That would be a similar use case to https://github.com/sindresorhus/Plash/issues/1#issuecomment-576498540 or https://github.com/sindresorhus/Plash/issues/1#issuecomment-573513816

**Comment by sindresorhus** [comment]
This is now available: https://twitter.com/sindresorhus/status/1376948053525950466
