### ISSUE TITLE
Allow user to enable/disable click-to-scale

### ISSUE THREAD

**Issue by colejd** [sindresorhus/Plash#48]
Currently there's a feature that lets the user click on the desktop to change the scaling. When I click on the desktop to defocus a window, this triggers that function of Plash; I absent-mindedly do this, so it happens a lot. My request is that the user is allowed to disable this feature, or barring that, require that Plash is focused in order to register the click.

**Comment by sindresorhus** [comment]
This is actually a bug. I don't plan a new release for a while, but you can get the fix here: https://install.appcenter.ms/users/sindresorhus/apps/plash/distribution_groups/public
