### ISSUE TITLE
Add aspect fill / fit option

### ISSUE THREAD

**Issue by colejd** [sindresorhus/Plash#49]
When displaying an image, Plash resizes to fit the image within the boundaries of the screen while keeping the aspect ratio. If the source image isn't the same aspect ratio as the screen (minus the toolbar height), the left and right sides will be cropped in and you can see the original desktop underneath.

My request is that an aspect fill option is added. Plash could then be an arbitrary size and the image would be guaranteed to fill the whole thing.

**Comment by sindresorhus** [comment]
I think we should just do this by default if the image is large enough.
