### ISSUE TITLE
Gap at top of screen when menu bar is hidden

### ISSUE THREAD

**Issue by jonthesquirrel** [sindresorhus/Plash#51]
**Describe the bug**

When the macOS menu bar is hidden, there is a gap at the top of the screen.

**To reproduce**

Enable "Automatically hide and show the menu bar" in System Preferences > General.

**Expected behavior**

Plash should fill the whole desktop if the menu bar is hidden.

**Screenshots**

![Screen Shot 2020-05-12 at 1 35 10 AM](https://user-images.githubusercontent.com/6022168/81661627-40b18a80-93f1-11ea-8f98-c7162d8e6ac9.png)

**Info**

 - macOS version: 10.15.4 (19E287)
 - Plash version: 1.4.0 (6)

**Comment by sindresorhus** [comment]
An update is out that fixes this. Just go to https://apps.apple.com/no/app/plash/id1494023538?mt=12 and click "Update".
