### ISSUE TITLE
Signing into OAuth apps closes the page

### ISSUE THREAD

**Issue by jpranaymartin** [sindresorhus/Plash#52]
When trying to sign-in to an app that navigates to an OAuth interstitial, the closing of the login page closes the Plash page instead of navigating to the app being signed into. 

Being able to sign into a Notion.so page or similar would be a great use case but seemingly doesn't work. I use the "Sign in with Google" option which is where the problem lies. 

---
Plash 1.5.1 (8) - com.sindresorhus.Plash
macOS 10.15.4
MacBookPro16,1

**Comment by sindresorhus** [comment]
Could you try this build and let me know if it fixes it for you?

[Plash-popup-fix.zip](https://github.com/sindresorhus/Plash/files/4688047/Plash-popup-fix.zip)

**Comment by jpranaymartin** [comment]
That fixed it! The sign-in pop-up now opens in a separate window and I'm able to sign in correctly. Looks like the session works across restarts of Plash too, which is fantastic. 

Thanks!!

**Comment by sindresorhus** [comment]
This fix is now out in the App Store.
