### ISSUE TITLE
Allow logging into sites that use Basic Auth

### ISSUE THREAD

**Issue by garand** [sindresorhus/Plash#58]
I have an internal company dashboard/monitoring tool that would be perfect to have on the desktop, however it is behind HTTP Basic Auth. When I set it as the background I didn't see any prompts for the username/password and the background remained blank.

It would be great to either be prompted for the username/password or provide it when setting the URL. Possibly inputs hidden behind a "Requires Authentication" checkbox next to the URL field?

![image](https://user-images.githubusercontent.com/82437/92493398-765d5900-f1c2-11ea-9da4-7cad71cfbd0a.png)

**Comment by sindresorhus** [comment]
This will be part of the next Plash update planned in a couple of weeks.

**Comment by garand** [comment]
Awesome, thanks! 🎉
