### ISSUE TITLE
URL variables

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/Plash#6]
I could be useful to expose some URL template variables.

The main problem I'm trying to solve is the tip in the readme:

<img width="923" alt="Screenshot 2020-01-09 at 20 06 11" src="https://user-images.githubusercontent.com/170270/72070192-83683680-331b-11ea-9e69-cd5f86f9c1e1.png">

It requires the user to manually find their screen resolution and then subtract the menu bar height.

Instead, it could simply be:

```
https://source.unsplash.com/random/{screenWidth}x{screenHeight}?puppy
```

Thoughts? Any other template variables that could be helpful?

**Comment by colejd** [comment]
Maybe a separate variable for screen height minus the toolbar height? I dunno if you need to hardcode 22/44 in, but if you do it'd be nice to have the raw screen height. That way, if macOS changes and Plash doesn't, I can compensate manually until it does.

**Comment by colejd** [comment]
Not sure if this works but I'm reading you can fetch the menu bar height with `[NSMenu menuBarHeight]`.

**Comment by sindresorhus** [comment]
> Maybe a separate variable for screen height minus the toolbar height?

The default variables should be without the menu bar height.

**Comment by sindresorhus** [comment]
> Not sure if this works but I'm reading you can fetch the menu bar height with [NSMenu menuBarHeight].

That wouldn't work here as Plash doesn't have a menu bar of its own. Plash already has a method to get the correct width/height: https://github.com/sindresorhus/Plash/blob/9f528fc83466ebc6cc092b75491b255258589b6f/Plash/util.swift#L1918
