### ISSUE TITLE
Wallpaper is not full screen.

### ISSUE THREAD

**Issue by fxnoob** [sindresorhus/Plash#62]
**Describe the bug**
Generated wallpaper is not covering the fullscreen
Generated wallpaper is not covering the fullscreen
**To reproduce**
I've just toggled the top menubar from settings.

wallpaper should be full screen.

**Screenshots**
![Screenshot 2020-09-24 at 7 01 59 PM](https://user-images.githubusercontent.com/24789277/94152565-581d7b80-fe99-11ea-8357-1e6e46e72920.png)
![Screenshot 2020-09-24 at 7 06 52 PM](https://user-images.githubusercontent.com/24789277/94152575-5c499900-fe99-11ea-92b6-d0922ec85f13.png)

**Info**

 - macOS version: 10.15.6 (19G73)
 - Plash version: from commit a88a122ddd20689e8d3627360956a82d080c3cd6

**Comment by sindresorhus** [comment]
What is the URL? Can you reproduce with other websites too?

**Comment by fxnoob** [comment]
@sindresorhus URL was  https://trends.google.com/trends/hottrends/visualize?pn=p1. I can see the same issue on https://windy.com  too. I haven't tried any others.
Though it goes away if i uncheck the toggle settings for menubar.

**Comment by sindresorhus** [comment]
Hmm. It works perfectly for me when hiding the menu bar.

Can you take a screenshot of your "Mission Control" system preferences and post it here?

<img width="780" alt="Screen Shot 2020-09-25 at 01 23 46" src="https://user-images.githubusercontent.com/170270/94209936-c3814080-fecd-11ea-8de3-c208189db12f.png">

**Comment by fxnoob** [comment]
Its same. just to let you know I've dock in the right. 
![Screenshot 2020-09-25 at 5 43 33 AM](https://user-images.githubusercontent.com/24789277/94212589-37354480-fef2-11ea-80fa-3c28e303d826.png)
 
![Screenshot 2020-09-25 at 5 42 46 AM](https://user-images.githubusercontent.com/24789277/94212499-f89f8a00-fef1-11ea-8f0a-134b45fe842a.png)
