### ISSUE TITLE
Add currently focused app to query string.

### ISSUE THREAD

**Issue by KevinBatdorf** [sindresorhus/Plash#64]
Is this possible? I want to build a "cheat sheet" type web app that will load the data based on a query string. So for example, if vs code is focused, the url would be dashboard.test/?focusedapp=vscode and it would ideally be reactive (without page refresh) so that the web application could monitor the query string.

**Comment by sindresorhus** [comment]
This sounds like a fun thing, but your request is a little bit too specific to your needs and not something most would need, so I don't think it makes sense to add it to Plash. However, Plash is open source and it should not be hard to add it in your own fork. You could also consider using Electron for this, combined with https://github.com/sindresorhus/active-win
