### ISSUE TITLE
Support navigator.mediaDevices / WebRTC

### ISSUE THREAD

**Issue by hauswirth** [sindresorhus/Plash#65]
**Is your feature request related to a problem? Please describe.**

navigator.mediaDevices returns undefined.

See, e.g., https://webrtc.github.io/samples/src/content/devices/input-output/

**Describe the solution you'd like**

I don't know WebKit, but maybe this could be an approach:

https://bugs.webkit.org/show_bug.cgi?id=183201#c31

https://github.com/OpenTelecom/WKWebViewRTC

While that solution seems specific to iOS, maybe it could be adapted to macOS?

**Describe alternatives you've considered**

Currently, simply not using Plash but putting a QuickTime Player window behind all other windows. But using a web page in Plash for that would be much more convenient and configurable.

**Additional context**

Webcam support in Plash's browser would allow the creation of web pages that show the webcam on the desktop. This would be a great for online presentations: one can share the screen, use Plash with the webcam video as the desktop background, and play a presentation or do other things in windows on top.

**Comment by sindresorhus** [comment]
I understand the need, but I'm unfortunately not interested in adding this to Plash. First, it's only available for iOS at the moment, and second, it's a pretty big dependency, which comes with a lot of risks. For example, I will have to deal with any bugs in that implementation as users will not know or care that the fault is in a dependency.

Instead, I would follow https://bugs.webkit.org/show_bug.cgi?id=188360 and hope that Apple will realize it's important.

You could also try submitting a feature request through the Feedback Assistant app.
