### ISSUE TITLE
Enable audio option

### ISSUE THREAD

**Issue by jpeiniger** [sindresorhus/Plash#67]
Would it be possible to enable audio optionally? 

I am building a work timer and would like to play a nice chinese gong sound, when I am in for a little break after a given amount of time. 

Doing this with react, but I cannot get audio working.

**Comment by sindresorhus** [comment]
Sorry, I don't plan to add this. Plash is intended to be for dynamic wallpapers. I fear this is a slippery slope of Plash turning into a browser or Electron.

That being said, I have done a custom build for you with audio enabled: [Plash-with-audio.zip](https://github.com/sindresorhus/Plash/files/5633717/Plash-with-audio.zip)

**Comment by aspdev91** [comment]
Hi @sindresorhus by any chance, do you have an audio enabled version for the latest release?

**Comment by sindresorhus** [comment]
The next version of Plash will have a "Mute audio" preference. It will be out in a month or so.

Here's a build with the preference: [Plash-audio-setting.zip](https://github.com/sindresorhus/Plash/files/7191091/Plash-audio-setting.zip)

**Comment by aspdev91** [comment]
@sindresorhus Thank you

**Comment by sindresorhus** [comment]
I decided to do a new release, so this preference is now included in the App Store version: https://apps.apple.com/no/app/plash/id1494023538?mt=12

**Comment by aspdev91** [comment]
Thanks for the update =)
