### ISSUE TITLE
Allow browsing mode to click through the transparent parts

### ISSUE THREAD

**Issue by imaverage** [sindresorhus/Plash#68]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I have to toggle the browsing mode on and off when I want to click a link in my dashboard. that little links widget is always visible on my screen. But I can't leave browsing mode on because I can't click my normal apps on my desktop even through the transparent parts of my plash app. 

**Describe the solution you'd like**

I wish I could have the browsing mode enabled and be able to click through the empty parts to my apps on my desktop. my widget is only like 200px x 200px so i wish it worked more like a widget than a fullscreen app in the sense that i could click through the transparent parts that im not using.

**Describe alternatives you've considered**

i created a bash script and added it to my dock which lets me easily toggle the browsing mode on and off without needing my keyboard. annoying though.

**Additional context**

![image](https://user-images.githubusercontent.com/73820097/103376477-5bc92b80-4aa2-11eb-92c7-1e98480c590a.png)

cant click through see it selects texts or empty space instead of clicking my calculator app

**Comment by imaverage** [comment]
the zip artifact in https://github.com/sindresorhus/Plash/issues/50 seems to resolve this well enough, even if it's not an official release. thanks!

**Comment by sindresorhus** [comment]
I'm not sure whether or not it's actually possible. This is not something I plan to work on, but a good pull request would be welcomed, but the technical implementation should be described and approved here first. This would also have to be opt-in.

This is mutually exclusive with https://github.com/sindresorhus/Plash/issues/50. I don't intend to support both, so we need to decide which solution is the best.

**Comment by imaverage** [comment]
i like the way it is with #50 it is a superior solution to what i had proposed. this can be closed now, but i would request that the "browsing mode" be something that is remembered "Start in browsing mode" since that actually has a use case now.

**Comment by sindresorhus** [comment]
Closing in favor of #50.

Here's a build where "browsing mode" is persisted. Would you be able to try it out and let me know how it works for you?

[Plash-persisted-browsing-mode.zip](https://github.com/sindresorhus/Plash/files/5786384/Plash-persisted-browsing-mode.zip)

**Comment by imaverage** [comment]
it works, good work! 

out of curiosity, how long do you plan to maintain this project? it's really nice that you do, but im not sure how much faith to have in that it will stay that way. i have started placing a rather large dependency on this app and want to see it survive through the upcoming mac upgrades

**Comment by sindresorhus** [comment]
Thanks for testing. I don't plan on doing a new release soon, so just continue using this build until the new version is out.

---

> out of curiosity, how long do you plan to maintain this project? it's really nice that you do, but im not sure how much faith to have in that it will stay that way. i have started placing a rather large dependency on this app and want to see it survive through the upcoming mac upgrades

Indefinitely. I actively maintain all of my apps and open source projects. My full-time job is open-source. I've been doing open-source for 10 years and I don't plan to stop.

**Comment by sindresorhus** [comment]
And please share in https://github.com/sindresorhus/Plash/issues/1 if you're using Plash for something interesting and you're allowed to share it.
