### ISSUE TITLE
Does not load sometimes

### ISSUE THREAD

**Issue by imaverage** [sindresorhus/Plash#71]
**Describe the bug**

Oftentimes when I load the computer, Plash isn't visible. Even if i go to the menu and click reload. I have to manually kill the app and restart it and it works. 

**To reproduce**

1. Set plash to start on load
2. Restart mac
3. Nondeterministically, notice it isn't visible until you kill and restart the app
4. notice its now visible after restart

**Expected behavior**

Should be visible on login. Alternatively/additionally, a way to tell the app to refresh (like via applescript).

**Screenshots**

**Info**

 - macOS version: 10.15.6
 - MBP (16in, 2019)
 - Plash version: `Version 1.7.0-browsing-mode (11)`

**Additional context**

**Comment by imaverage** [comment]
If I had to guess, I'd say it's something about the application not mounting or being laid onto the desktop properly.

**Comment by sindresorhus** [comment]
Can you check if you can reproduce this with the App Store version of Plash too? Just to rule out recent changes in Plash being the cause.

**Comment by sindresorhus** [comment]
Hmm, maybe Plash launches before your computer is able to connect to the internet, and since it's not connected, it gets into a weird state or something. I'm just guessing, as I haven't yet been able to reproduce this.

**Comment by sindresorhus** [comment]
Did you have "browsing mode" activated?

**Comment by imaverage** [comment]
> Hmm, maybe Plash launches before your computer is able to connect to the internet, and since it's not connected, it gets into a weird state or something. I'm just guessing, as I haven't yet been able to reproduce this.

probably not. I turned off plash, turned off my wifi (and not connected to anything), and opened plash and it loads the widgets fine but the widgets are empty (as they widgets pull from internet). its a locally complied react html app.

> Did you have "browsing mode" activated?

yes

**Comment by sindresorhus** [comment]
> Can you check if you can reproduce this with the App Store version of Plash too? Just to rule out recent changes in Plash being the cause.

⏫

**Comment by imaverage** [comment]
My app store download didn't finish, just gets stuck at 99% :/.

That said, I was able to reproduce it consistently by doing this:
* set chrome to full screen mode
* focus chrome desktop
* run `pkill -9 Plash; sleep 3; open -a Plash` in some background app while your main desktop is not focused
* notice that Plash doesn't load properly when you go to your primary empty desktop

**Comment by sindresorhus** [comment]
I think I found a fix to this. Can you test? https://dsc.cloud/sindresorhus/Plash.app-1613643403

Your issue is happening because Plash opens in the current space, and fullscreen windows are "Spaces", so Plash opens behind the Chrome window. I'm now forcing Plash to not open in spaces that are fullscreen windows.

**Comment by imaverage** [comment]
works great
