### ISSUE TITLE
Rendering freezes until provoked sometimes

### ISSUE THREAD

**Issue by imaverage** [sindresorhus/Plash#72]
**Describe the bug**

A display freezes (is interactive) but does not repaint until provoked manually somehow.

**To reproduce**

1. Toggle an element (so its hidden)
2. note it does not repaint
3. right click, view element inspector
4. see repaint

**Expected behavior**

it should repaint without being manually retriggered

**Screenshots**

two videos attached. one is the error on plash. one is the lack of that error when viewing that same html file in firefox.

https://user-images.githubusercontent.com/73820097/105654957-ba58ae00-5e84-11eb-9ca2-02db889cf948.mov

https://user-images.githubusercontent.com/73820097/105654899-9bf2b280-5e84-11eb-9630-68107d8605e0.mov

**Info**

 - macOS version: 10.15.7
 - Plash version: `Version 1.7.0-browsing-mode (11)`

**Additional context**

**Comment by sindresorhus** [comment]
Are you able to reproduce this with any public websites? (So I can reproduce it myself)

**Comment by imaverage** [comment]
I just tried https://demos.creative-tim.com/material-dashboard-pro-react/#/admin/dashboard but it loaded fine. maybe I just wrote some crap code that's causing the rendering issues as opposed to plash? can't reproduce it outside of plash though (like in chrome)

**Comment by imaverage** [comment]
looks like it might be related to using `display: flex`
