### ISSUE TITLE
Could not support input in Chinese 

### ISSUE THREAD

**Issue by leodknuth** [sindresorhus/Plash#75]
Hi @sindresorhus ,

I found Plash could not support Chinese input method on website desktop. Will you fix the bug? Plash is an amazing app! thanks.

**Comment by sindresorhus** [comment]
Can you include some more information? Do you mean that you tried writing Chinese on a website and it didn't work? Would you be able to share the website? Make sure you're in "Browsing Mode" as otherwise you cannot write in an language.
