### ISSUE TITLE
App Center Download in README.md is Outdated

### ISSUE THREAD

**Issue by thatrobotdev** [sindresorhus/Plash#77]
Hello!

I was looking at the [App Center download](https://install.appcenter.ms/users/sindresorhus/apps/plash/distribution_groups/public) [mentioned in the README.md,](https://install.appcenter.ms/users/sindresorhus/apps/plash/distribution_groups/public) which is supposed to be the latest commit, but it looks outdated (the most recent release is Version 1.4.0 from March 14th, 2020.

**Comment by sindresorhus** [comment]
It’s outdated as AppCenter has not updated their Xcode version so it doesn’t build. I'll hide it for now.
