### ISSUE TITLE
Ad-blocking support

### ISSUE THREAD

**Issue by xplosionmind** [sindresorhus/Plash#82]
**Is your feature request related to a problem? Please describe.**

My current Plash page is the main page of a news website. It is clammed with ads. Since the purpose of having a webpage as the desktop wallpaper is having the most important things ready at a glance, this becomes useless since 2/3 of the page are made of ads, and only 1/3 of news.

<br>

**Describe the solution you'd like**

Either:
- the ability of choosing an installed browser (e.g. Firefox) as the rendering engine, together with all of the extensions it includes. In this way, I would have the page beautifully displayed.
- adding an ad-blocking service, embedded in Plash. Since uBlock Origin is open source, I do not think it is a hard task.

<br>

**Describe alternatives you've considered**

- Keeping the homepage as-is
- changing news website, even if most of them have the same issue

**Comment by sindresorhus** [comment]
> the ability of choosing an installed browser (e.g. Firefox) as the rendering engine, together with all of the extensions it includes. In this way, I would have the page beautifully displayed.

This is not possible. Plash deeply depends on the bundled WebKit version in macOS.

> adding an ad-blocking service, embedded in Plash. Since uBlock Origin is open source, I do not think it is a hard task.

A web view is not the same as a full browser. Plash uses a web view. It's not possible to directly integrate a Safari extension.

**Comment by sindresorhus** [comment]
Duplicate of #37

**Comment by xplosionmind** [comment]
I am sorry, my bad. I missed the duplicate issue. Thanks a lot anyways!
