### ISSUE TITLE
Automatic color-inversion in dark mode

### ISSUE THREAD

**Issue by xplosionmind** [sindresorhus/Plash#83]
**Is your feature request related to a problem? Please describe.**

Right now, when I activate dark mode in my settings, I may still have a super bright background which does not adapt to the rest of the UI theme.

<br>

**Describe the solution you'd like**

It would be great if site-specific color inversion could be selected, in order to automatically make the wallpaper dark if dark mode is on, and reverting to the standard colors when light mode is back. In the same way, for dark websites the color inversion should be activated only if light mode is on.

<br>

**Describe alternatives you've considered**

Switching manually to a dark website when the dark theme comes into play, or always keeping color inversion on, even if when light theme is on readability would be decreased.

**Comment by sindresorhus** [comment]
This is now available in the latest update: https://apps.apple.com/no/app/plash/id1494023538?mt=12
