### ISSUE TITLE
Unable to set keyboard shortcuts

### ISSUE THREAD

**Issue by xplosionmind** [sindresorhus/Plash#84]
**Describe the bug**

When I try to set shortcuts, nothing is recorded.

<br>

**To reproduce**

1. Go to 'Preferences' > 'Shortcuts'
2. Click on 'Record shortcut'
3. Press the shortcut keys
4. nothing appears

<br>

**Expected behavior**

The keys I pressed appear in the input box.

<br>

**Screenshots**

<img width="342" alt="Screenshot 2021-06-02 at 11 14 04 AM" src="https://user-images.githubusercontent.com/42862428/120453832-e3350680-c382-11eb-99e1-16869ad642f1.png">

<br>

**Info**

 - macOS version: 11.4
 - Plash version: 2.2.0

**Comment by xplosionmind** [comment]
The shortcut I was trying to register was `cmd` + `shift` + `B`. If I press it normally when I am in my desktop, nothing happens… therefore, it should not be used for other tasks by other apps. Nevertheless, some more complicated shortcuts are effectively registered, so I guess this is not a bug.

**Comment by sindresorhus** [comment]
I'm able to add that:

<img width="452" alt="Screen Shot 2021-06-09 at 16 36 37" src="https://user-images.githubusercontent.com/170270/121331219-dd21c580-c940-11eb-8fa8-b5d892e63dd3.png">


---

> If I press it normally when I am in my desktop, nothing happens… therefore, it should not be used for other tasks by other apps.

That doesn't mean it's not taken. Try quitting all open apps and menu bar apps and see if it still doesn't work.

Anyway, there's unfortunately no way for Plash to inform you which app has taken a specific shortcut as when the shortcut is taken, it's never passed to Plash at all.
