### ISSUE TITLE
Allow cookie access so google sheets can show up

### ISSUE THREAD

**Issue by noa-no-h** [sindresorhus/Plash#86]
Hello! 

First of all, thanks for the wonderful app! I'm really enjoying it!
When I try to go to google sheets, however, it says "Google Sheets needs access. Google Sheets needs to authenticate your session. Please allow cookie access for Google Sheets by clicking here." Then when I click on the "here", it tells me "cookie access failed." Is cookie access something that can be added?
Thanks!

**Comment by sindresorhus** [comment]
What macOS version? Can you confirm that you're on the latest Plash version? I assume it's https://sheets.google.com ?

**Comment by sindresorhus** [comment]
Can you try out this build: https://dsc.cloud/sindresorhus/Plash.app-1625749911 ?

**Comment by noa-no-h** [comment]
Thank you so much for the quick reply! This unfortunately just made the google sheets iframe entirely white. (I just realized I didn’t mention this is an iframe inside a google site. I don’t know if that makes any difference.)

**Comment by noa-no-h** [comment]
MacOS 11.4 and before I downloaded the build you sent, I was using the one on the mac store downloaded yesterday

**Comment by noa-no-h** [comment]
Ah ha! I tried opening a new backround website that was just sheets without any iframe, signed in there, returned to my original website, and it worked! Thank you so much for your help!

**Comment by sindresorhus** [comment]
Which one worked, this build, App Store, or both?

**Comment by noa-no-h** [comment]
Sorry for the late reply. They both work now although the App Store build grays out the iframes slightly (Not too much to read but just a little annoying). ---- On Thu, 08 Jul 2021 10:38:47 -0700  ***@***.******@***.***> wrote ---- 
Which one worked, this build, App Store, or both?
