### ISSUE TITLE
`localhost` URLs without `.` aren't supported

### ISSUE THREAD

**Issue by cherryblossom000** [sindresorhus/Plash#87]
**Describe the bug**

`localhost` URLs that do not contain a `.` character cannot be added because the ‘Add’ button is disabled.

**To reproduce**

1. Click ‘Add website…’
2. Type `http://localhost:3000` for the website
3. Type anything (e.g. ‘some title’) for the title

**Expected behavior**

The ‘Add’ button should be enabled.

**Info**

 - macOS version: 11.5.2
 - Plash version: 2.3.1

**Additional context**

Related: #28

I think the issue is due to this:

https://github.com/sindresorhus/Plash/blob/823e9032944e49a11df040aae26a36a8a1aaa246/Plash/AddWebsiteView.swift#L22-L29

I don’t think the `urlString.contains(".") || urlString.hasPrefix("file://")` (and the same with `urlString2`) is necessary because that should be handled here:

https://github.com/sindresorhus/Plash/blob/823e9032944e49a11df040aae26a36a8a1aaa246/Plash/Utilities.swift#L952-L982

As a workaround, I set the website to `http://localhost:3000/index.html`.

**Comment by sindresorhus** [comment]
Fixed in the latest Plash update.
