### ISSUE TITLE
Plash prevents access to Desktop during "Show Desktop" 

### ISSUE THREAD

**Issue by sinkva** [sindresorhus/Plash#89]
> 

Plash running, invoke "Show Desktop". Clicks on Desktop don't work, active app doesn't switch to Finder.
Plash not running, invoke "Show Desktop". Clicks on Desktop switches to Finder.

---
Plash 2.4.0 (21) - com.sindresorhus.Plash
macOS 11.4.0
iMac21,1

**Comment by sindresorhus** [comment]
This is a known bug in macOS 11... It seems like macOS 12 will fix this, which will be out in a month or two.

**Comment by dave-holland** [comment]
> This is a known bug in macOS 11... It seems like macOS 12 will fix this, which will be out in a month or two.

macOS 12 up to beta 7 hasn't fixed the issue. Is there a potential workaround?

**Comment by sindresorhus** [comment]
I was sure I could not reproduce when testing an earlier macOS 11 beta. Weird.

**Comment by sindresorhus** [comment]
There's an update out now that works around the issue: https://apps.apple.com/no/app/plash/id1494023538?mt=12

**Comment by weranda** [comment]
> There's an update out now that works around the issue: https://apps.apple.com/no/app/plash/id1494023538?mt=12

👍

**Comment by sinkva** [comment]
Thanks!
