### ISSUE TITLE
Injecting Javascript from Command Line

### ISSUE THREAD

**Issue by aspdev91** [sindresorhus/Plash#90]
**Is your feature request related to a problem? Please describe.**

I'd like to enable dark mode. If there's a way to inject javascript into the website, that would be great as well for other use cases.

**Describe the solution you'd like**

Ability to inject javascript or set dark mode natively.

**Describe alternatives you've considered**

I noticed there's a mention of dark mode in the documentation. I couldn't find where to enable it in the software.

**Comment by sindresorhus** [comment]
In the websites list, right-click, and select "Edit".

**Comment by aspdev91** [comment]
Thanks @sindresorhus 

I can update the documentation with instructions and a GIF if this is a common question.

**Comment by sindresorhus** [comment]
Nah, I'm gonna add something to the UI about it.
