### ISSUE TITLE
Fullscreen on YouTube

### ISSUE THREAD

**Issue by aspdev91** [sindresorhus/Plash#91]
**Is your feature request related to a problem? Please describe.**

I'm trying to full screen a Youtube video, but it says when I hover over the full screen button that full screen is not supported by this browser.

**Describe the solution you'd like**

The ability to turn on full screen.

**Describe alternatives you've considered**

**Comment by sindresorhus** [comment]
This is unfortunately not possible. The component Plash uses for showing websites does not support fullscreen-mode.

There are some possible workarounds:
- Find the direct URL to the video file and use that in Plash.
- Download the YouTube video and open it in Plash.
- Use CSS to make the player take up 100% width/height of the website.

**Comment by kidonng** [comment]
You can use the embed version: https://www.youtube.com/embed/watch?v=dQw4w9WgXcQ

**Comment by aspdev91** [comment]
Thanks for the help on this.

To clarify, I'd like to full screen from a Miro board and that's where the
message is coming up.

**Comment by kidonng** [comment]
Then sadly, I don't think it's possible at the moment.

**Comment by sindresorhus** [comment]
This was fixed in the latest update (2.10.0).
