### ISSUE TITLE
Prevent from adding a website if an URL already exists

### ISSUE THREAD

**Issue by vladstudio** [sindresorhus/Plash#92]
**Is your feature request related to a problem? Please describe.**

Hi! I'm Vlad from Vlad.studio – I'd like to direct my website users to Plash app and provide them with handy links to open various features of my website in Plash, using "plash:" URL scheme (plash:add?url=...).

Problem is – if I click same "plash:add" link twice, two identical websites are added. 

**Describe the solution you'd like**

Do not allow adding a website (either from preferences or from plash:add URL) if a website with the same URL already exists.

**Comment by sindresorhus** [comment]
What if the user actually wants two websites? They might want to apply different settings to each.

**Comment by sindresorhus** [comment]
> Problem is – if I click same "plash:add" link twice, two identical websites are added.

Is this actually a problem in practice? Do people actually click the link twice without intending to do so?

**Comment by vladstudio** [comment]
> Is this actually a problem in practice? Do people actually click the link twice without intending to do so?

I do not yet know :-) 

> What if the user actually wants two websites? They might want to apply different settings to each.

Does it happen in practice? (I'm not saying it does not, just curious).

Anyway, this seems like a minor enhancement, please feel free to close / postpone infinitely.

**Comment by sindresorhus** [comment]
Are you worried people will accidentally click the link quickly twice in a row? Or that they will first click it and then later on click it again, having forgotten that they initially clicked it? For the former, I could maybe add some kind of debouncing, so it would deduplicate accidental double-clicks.

**Comment by sindresorhus** [comment]
> Does it happen in practice? (I'm not saying it does not, just curious).

Probably not very often, but I also don't want to prevent it. Let's say there's a website that shows dynamic content, but each unique content on the page does not have a separate URL, so the user must open the same page multiple times and click to it in each to get the separate content. Or it could be that they want different scroll positions for a website.

**Comment by sindresorhus** [comment]
Closing for now. Can reopen if it's actually a problem for users in practice.
