### ISSUE TITLE
Access webpages faster by launching them with dedicated shortcuts

### ISSUE THREAD

**Issue by raasoft** [sindresorhus/Plash#94]
I use the tool as a quick shortcut to access some webpages that I have to use for work and that I should keep open no matter what.

Basically  I use Chrome to only open "temporary pages" that I could close, while I prefer to keep "essentials" that should never be closed and always available on Plush (like Trello to quickly create a new task while I am in a meeting, Google Calendar to quickly book someone, etc.)

It would help me to access the right page at the right moment (usually I need this during meetings, where I have to be blazing fast) the possibility to define a shortcut for a specific page, instead of opening a page and then cycle through them until I find the right one (I don't always remember where I am when I cycle, and cycling is slow because it has to reload the page and takes ~500ms)

Many thank you!

---
Plash 2.6.0 (23) - com.sindresorhus.Plash
macOS 12.0.1
MacBookPro17,1

**Comment by sindresorhus** [comment]
I decided to make this possible using the Shortcuts app instead of adding built-in support: https://github.com/sindresorhus/Plash/releases/tag/v2.7.0

**Comment by raasoft** [comment]
Hi! Many thank you for that! How can I apply the latest release? Should I build it from scratch or is it a possibility to see it in apple store automatically?

**Comment by sindresorhus** [comment]
It's available as an update in the App Store. Go to https://apps.apple.com/no/app/plash/id1494023538?mt=12 and click "Update".
