### ISSUE TITLE
Add how to compile source code to create .dmg file

### ISSUE THREAD

**Issue by vikbert** [sindresorhus/Plash#95]
Could you please add the How-to to README, so that we can create *.dmg from the source code. For some privacy reason, we are not able to install the application from apple app store.

**Comment by sindresorhus** [comment]
Plash is just a normal app with no special compile requirements, so you can search for any guide on how to compile apps with Xcode and how to make a DMG. I don't think this is the place to document that. The official way to get Plash is through the App Store. The code is open source and you're free to compile it as you see fit, but I'm not interested in providing support for that. I hope you understand.
