### ISSUE TITLE
What about supporting multiple areas/workspaces on one screen？

### ISSUE THREAD

**Issue by JasoxHsueh** [sindresorhus/Plash#96]

**Comment by sindresorhus** [comment]
I think that's outside the scope of Plash.

You can kinda solve this with `iframe`/`frameset` as long as the website you want doesn't prevent being embedded in an iframe. There are of course ways around this by using a proxy server that strips the `Content-Security-Policy` header.

I do want to make a different app where you can open multiple web browser windows as widgets on the desktop, but it's not something I will be able to work on anytime soon.
