### ISSUE TITLE
webpage seems to be reloaded in a random time

### ISSUE THREAD

**Issue by unnownmn** [sindresorhus/Plash#97]
I do not turn on the  Reload interval feature， but my webpage seems to be reloaded in a random time。

---
Plash 2.7.1 (25) - com.sindresorhus.Plash
macOS 12.1.0
Macmini8,1

**Comment by sindresorhus** [comment]
What website? Some websites refresh theirselves. It sounds like that is what's happening in your case. There's no way for Plash to prevent that.
