### ISSUE TITLE
Plash icon doesn't display in menubar

### ISSUE THREAD

**Issue by linroex** [sindresorhus/Plash#98]
**Describe the bug**

I enable "hide icon in menubar" in Plash setting, in my menory, the hint say "open Plash again then icon display" (not sure), but when I open Plash again, nothing happen.

**Info**

 - macOS version: 12.1
 - Plash version: 2.7.1

**Comment by linroex** [comment]
I go to terminal close Plash app, and open again, then icon display

**Comment by sindresorhus** [comment]
This is caused by a macOS 12 bug. I'll get a workaround out shortly.

https://github.com/feedback-assistant/reports/issues/246

**Comment by sindresorhus** [comment]
This is now fixed in the latest update.
